### ISSUE TITLE
Adding a column to the download section that shows nimplant details

### ISSUE THREAD

**Issue by x0ri9922** [chvancooten/NimPlant#12]
- [x] This issue is not about OPSEC or bypassing defensive products

---

**Feature Description**
It would be nice to add a column in the download page where you can see what computer is related to the downloaded file.

**Comment by chvancooten** [comment]
Thanks, that's a great suggestion. Will add it to my to-do list for v1.2!

**Comment by chvancooten** [comment]
Hey! I added indication of a download's nimplant GUID as well as some basic information about that nimplant to the downloads screen in https://github.com/chvancooten/NimPlant/commit/39f09445b53cdbbcd798bc9fb319722a79391029 (currently dev, will be pushed to main as part of v1.2). Let me know if this was what you had in mind, or if you have any further suggestions!

![image](https://user-images.githubusercontent.com/25614522/222917294-91bacaa8-e56f-41fa-b14f-6b5c26576819.png)
