### ISSUE TITLE
sh: 1: nim: not found

### ISSUE THREAD

**Issue by Pen-Ace** [chvancooten/NimPlant#13]
Great work here bro. I am looking to review this under my C2 reviews. 

I am running the server on Kali Linux, but encountering errors while attempting to generate the compile command and add it to the Client/bin directory.

the "all" command generates this:

Compiling .exe for NimPlant
/home/kali/Desktop/NimPlant/client/util/functions.nim(1, 8) Error: cannot open file: parsetoml
Compiling self-deleting .exe for NimPlant
/home/kali/Desktop/NimPlant/client/util/functions.nim(1, 8) Error: cannot open file: parsetoml
Compiling .dll for NimPlant
/home/kali/Desktop/NimPlant/client/util/functions.nim(1, 8) Error: cannot open file: parsetoml
Compiling .bin for NimPlant
/home/kali/Desktop/NimPlant/client/util/functions.nim(1, 8) Error: cannot open file: parsetoml
Traceback (most recent call last):
  File "/home/kali/Desktop/NimPlant/NimPlant.py", line 229, in <module>
    compile_implant(implant, binary, xor_key)
  File "/home/kali/Desktop/NimPlant/NimPlant.py", line 109, in compile_implant
    compile_function("raw", xor_key)
  File "/home/kali/Desktop/NimPlant/NimPlant.py", line 189, in compile_nim
    dll = open("client/bin/NimPlant.dll", "rb").read()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'client/bin/NimPlant.dll'

I did try: pip install toml - no luck.

Any help would be great.
Thanks
Ace

**Comment by chvancooten** [comment]
Hey @Pen-Ace, it looks like you haven't installed Nim dependencies correctly. Please use the Docker container, or install them locally. Per the readme: `Install required packages using the Nimble package manager (cd client; nimble install -d)`.

P.s., please follow the [issue template](https://github.com/chvancooten/NimPlant/tree/main/.github/ISSUE_TEMPLATE) next time ;)

**Comment by Pen-Ace** [comment]
Noted. Safe bro.
