### ISSUE TITLE
Enhancement  -- Live web cam Access

### ISSUE THREAD

**Issue by kali64amd** [chvancooten/NimPlant#17]
- [ ] This issue is not about OPSEC or bypassing defensive products

---

**Feature Description**

It would be nice if you Add this feature where user can see live web cam and get location.

**Comment by chvancooten** [comment]
Hi, thanks for the suggestion. Due to the fact that this feature has limited legitimate use cases (awareness presentations only, maybe) this is not on the to-do list for now. Feel free to submit a PR and I may consider merging it.
