### ISSUE TITLE
Compilation error in Parrot OS

### ISSUE THREAD

**Issue by virgilcj** [chvancooten/NimPlant#24]
```
──╼ $cat /etc/os-release 
PRETTY_NAME="Parrot OS 5.3 (Electro Ara)"
NAME="Parrot OS"
VERSION_ID="5.3"
VERSION="5.3 (Electro Ara)"
VERSION_CODENAME=ara
ID=parrot
ID_LIKE=debian

──╼ $python3 --version
Python 3.9.2
┌─[parrot@parrot]─[~/NimPlant]
└──╼ $nim --version
Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
```
**Using Docker:** No

---

**Issue Description**

Compiling error when installing on Parrot OS. Tried the same with kali and it works well. 

```
Compiling .exe for NimPlant
/home/parrot/.nimble/pkgs2/winregistry-1.0.0-30462eb902c219db72c018c4c3669ecaee08e107/winregistry.nim(66, 6) Error: undeclared identifier: 'useWinUnicode'
candidates (edit distance, scope distance); see '--spellSuggest': 
 (8, 2): 'NimNode'
```

There was one error when installing dependancies through: 
```
└──╼ $python3 -m pip install -r requirements.txt 
Ignoring prompt-toolkit: markers 'sys_platform == "win32"' don't match your environment

```

---

**Comment by chvancooten** [comment]
Hi, that's weird - it appears this is an upstream issue in https://github.com/miere43/nim-registry (the error `undeclared identifier: 'useWinUnicode'` seems to indicate the problem). I don't see any version bumps or changes that can be made on the Nimplant side to fix this - correct me if I'm wrong. I would suggest opening an issue there, and using the Nimplant Docker container to build implants in the meantime! You should still be able to run the web server on Parrot without issues.

**Comment by fukusuket** [comment]
Hi, I ran into the same problem(on macOS/ Ubuntu22.04). So, I created the following issue in `nim-registry`. 
- https://github.com/miere43/nim-registry/issues/10

This error occurs with Nim 2.0.0, but not with Nim 1.6.14.

**Comment by miere43** [comment]
@chvancooten hello, I fixed this issue in `winregistry v2.0.0`.

**Comment by virgilcj** [comment]
Thank you @miere43 , @fukusuket  @chvancooten .

**Comment by chvancooten** [comment]
Thanks for the quick fix @miere43!
@virgilcj, thanks again for reporting. I have bumped the versions for Nimplant and the [chvancooten/nimbuild](https://github.com/chvancooten/nimbuild) Docker container. Hopefully this issue should now be resolved for all new users as well :)
