### ISSUE TITLE
Adding a screenshot feature

### ISSUE THREAD

**Issue by sl4cky** [chvancooten/NimPlant#7]
- [x] This issue is not about OPSEC or bypassing defensive products

---

**Feature Description**
Would be great to have a screenshot feature where you can decide if you want to take 1 screenshot or a screenwatch like in CS :) How can this be implemented? Maybe I can help out some 👍

**Comment by chvancooten** [comment]
Hey @sl4cky, thanks for the suggestion! I agree that would be a good idea. I will look into a reference implementation for Nim and try to add it to the v1.1 version that is currently in the Dev branch. Will keep you updated :)

**Comment by sl4cky** [comment]
Great @chvancooten , would be awesome, let me know if you need any help with it. Liked you project, it's lightweight and could be great in engagements.

**Comment by chvancooten** [comment]
Thanks, but no need! It actually proved fairly easy to implement. Added in v1.1 which is in the Dev branch currently, hope to push it to main soon. Feel free to play with it in the meantime!
